config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from rest_framework.authtoken.views import obtain_auth_token

urlpatterns = [
                  path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
                  # Django Admin, use {% url 'admin:index' %}
                  path(settings.ADMIN_URL, admin.site.urls),
                  # User management
                  path("users/", include("zerone_inc.users.urls", namespace="users")),
                  path("accounts/", include("allauth.urls")),
                  # Your stuff: custom urls includes go here
                  # path("slack/", include("zerone_inc.attend.urls", namespace="attend")),
                  path("slack/", include("zerone_inc.zeroslack.urls", namespace="zeroslack")),
                  path("surveys/", include("zerone_inc.okr.urls", namespace="okr")),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("config.api_router")),
    # DRF auth token
    path("auth-token/", obtain_auth_token),
]

if 'survey' in settings.INSTALLED_APPS:
    urlpatterns += [
        path("survey/", include('survey.urls'))
    ]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

zerone_inc/okr/urls.py
from django.urls import path,re_path

from .views import SurveyList,ConfirmView, IndexView, SurveyCompleted, SurveyDetail,serve_result_csv

app_name = "okr"
urlpatterns = [
    # path("", view=event_hook, name="attend_event"),
    path("", view=SurveyList.as_view(), name="survey-list"),
    # url(r"^$", IndexView.as_view(), name="survey-list"),
    re_path(r"^(?P<id>\d+)/", SurveyDetail.as_view(), name="survey-detail"),
    re_path(r"^csv/(?P<primary_key>\d+)/", serve_result_csv, name="survey-result"),
    re_path(r"^(?P<id>\d+)/completed/", SurveyCompleted.as_view(), name="survey-completed"),
    re_path(r"^(?P<id>\d+)-(?P<step>\d+)/", SurveyDetail.as_view(), name="survey-detail-step"),
    re_path(r"^confirm/(?P<uuid>\w+)/", ConfirmView.as_view(), name="survey-confirmation"),
]

zerone_inc/users/urls.py
from django.urls import path

from zerone_inc.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

zerone_inc/zeroslack/urls.py
from django.urls import path

from . import views

from .api.views import AttendanceDashboard

app_name = "zeroslack"

urlpatterns = [
    path("dashboard/<int:year>/<int:month>/", views.ListAttendance.as_view(), name="dashboard"),
    path("table/<int:year>/<int:month>/", view=AttendanceDashboard.as_view(), name="dashboard-table"),
    path("events", views.events, name="handle"),
    path("install", views.oauth, name="install"),
    path("oauth_redirect", views.oauth, name="oauth_redirect"),
]

zerone_inc/attend/views.py
from django.db.models import F, Sum
from django.db.models.fields import DateField
from django.db.models.functions import Cast
from django.http import Http404
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.conf import settings
from django.views.generic import TemplateView
import jdatetime
from .models import Attendance
import logging

logger = logging.getLogger(__name__)


# Create your views here.


class ListAttendance(LoginRequiredMixin, TemplateView):
    template_name = "attend/graph.html"
    date_field = 'sign_in'

    def get_queryset(self):
        return Attendance.objects.filter(user=self.request.user).order_by('sign_in')

    def get_date_range(self, year, month) -> tuple:
        """Return the year for which this view should display data."""
        format = "%Y-%m"
        datestr = f"{year}-{month}"
        start_date = jdatetime.datetime.strptime(datestr, format).date()
        end_date = start_date + jdatetime.timedelta(days=30)
        try:
            return start_date.togregorian(), end_date.togregorian()
        except ValueError:
            raise Http404('Invalid date string “%(datestr)s” given format “%(format)s”' % {
                'datestr': datestr,
                'format': format,
            })

    def get_if_have_next_month(self, current_month):
        qs = self.get_queryset()
        x = qs.values_list('sign_in').latest('sign_in')[0]
        if current_month >= x.month:
            return False
        return True

    def get_if_have_prev_month(self, current_month):
        qs = self.get_queryset()
        x = qs.values_list('sign_in').earlist('sign_in')[0]
        if current_month >= x.month:
            return True
        return False

    def get_context_data(self, **kwargs):
        context = super(ListAttendance, self).get_context_data(**kwargs)
        year = self.kwargs.get('year', jdatetime.datetime.today().year)
        month = self.kwargs.get('month', jdatetime.datetime.today().month)
        qs = self.get_queryset()
        start_date, end_date = self.get_date_range(year=year, month=month)

        qs = qs.filter(sign_in__lte=end_date, sign_in__gte=start_date) \
            .annotate(length_of_stay=F('sign_out') - F('sign_in'),
                      day_of_work=Cast('sign_in', DateField())) \
            .values('day_of_work') \
            .order_by('day_of_work') \
            .annotate(stay_per_day=Sum('length_of_stay'))
        context['next_month'] = month + 1
        context['next_year'] = year
        context['prev_month'] = month - 1
        context['prev_year'] = year
        if month > 12:
            context['next_month'] = 1
            context['next_year'] = year + 1
        if month < 1:
            context['prev_month'] = 12
            context['prev_year'] = year - 1
        context['next_month_label'] = jdatetime.date(
            year=context['next_year'],
            month=context['next_month'],
            day=1).strftime('%B %Y')
        context['prev_month_label'] = jdatetime.date(
            year=context['prev_year'],
            month=context['prev_month'],
            day=1).strftime('%B %Y')
        if qs.count() > 0:
            context['attendance_list'] = qs
            context['attendance_overall'] = round(sum([i['stay_per_day'].seconds for i in qs]) / (192 * 3600),3)
            return context
        else:
            context['attendance_list'] = None
            return context

zerone_inc/okr/views.py
import logging
from datetime import date
from django.contrib import messages
from django.db.models import QuerySet
from django.shortcuts import redirect, render, reverse, get_object_or_404
from django.views.generic import ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.conf import settings
from django.views.generic import View, TemplateView
from django.contrib.auth.decorators import login_required
from django.http.response import HttpResponse

from .exporter.csv.survey2csv import Survey2Csv
from .decorators import survey_available
from .forms import ResponseForm
from .models import SurveyForUser, Response, Answer, Category, Survey, Question

LOGGER = logging.getLogger(__name__)


# Create your views here.

class SurveyList(LoginRequiredMixin, ListView):
    model = SurveyForUser
    template_name = 'okr/survey_list.html'

    def get_queryset(self) -> QuerySet:
        qs = self.model.objects.filter(user=self.request.user, is_valid=True)
        return qs


class ConfirmView(TemplateView):
    template_name = "okr/confirm.html"

    def get_context_data(self, **kwargs):
        context = super(ConfirmView, self).get_context_data(**kwargs)
        context["uuid"] = kwargs["uuid"]
        context["response"] = Response.objects.get(interview_uuid=kwargs["uuid"])
        return context


class IndexView(TemplateView):
    template_name = "okr/list.html"

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        surveys = Survey.objects.filter(
            is_published=True, expire_date__gte=date.today(), publish_date__lte=date.today()
        )
        if not self.request.user.is_authenticated:
            surveys = surveys.filter(need_logged_user=False)
        context["surveys"] = surveys
        return context


class SurveyCompleted(TemplateView):
    template_name = "okr/completed.html"

    def get_context_data(self, **kwargs):
        context = {}
        survey = get_object_or_404(Survey, is_published=True, id=kwargs["id"])
        context["survey"] = survey
        return context


class SurveyDetail(View):
    @survey_available
    def get(self, request, *args, **kwargs):
        survey = kwargs.get("survey")
        step = kwargs.get("step", 0)
        if survey.template is not None and len(survey.template) > 4:
            template_name = survey.template
        else:
            if survey.is_all_in_one_page():
                template_name = "okr/one_page_survey.html"
            else:
                template_name = "okr/survey.html"
        if survey.need_logged_user and not request.user.is_authenticated:
            return redirect("%s?next=%s" % (settings.LOGIN_URL, request.path))

        form = ResponseForm(survey=survey, user=request.user, step=step)
        categories = form.current_categories()

        asset_context = {
            # If any of the widgets of the current form has a "date" class, flatpickr will be loaded into the template
            "flatpickr": any([field.widget.attrs.get("class") == "date" for _, field in form.fields.items()])
        }
        context = {
            "response_form": form,
            "survey": survey,
            "categories": categories,
            "step": step,
            "asset_context": asset_context,
        }

        return render(request, template_name, context)

    @survey_available
    def post(self, request, *args, **kwargs):
        survey = kwargs.get("survey")
        if survey.need_logged_user and not request.user.is_authenticated:
            return redirect("%s?next=%s" % (settings.LOGIN_URL, request.path))

        form = ResponseForm(request.POST, survey=survey, user=request.user, step=kwargs.get("step", 0))
        categories = form.current_categories()

        if not survey.editable_answers and form.response is not None:
            LOGGER.info("Redirects to survey list after trying to edit non editable answer.")
            return redirect(reverse("okr:survey-list"))
        context = {"response_form": form, "survey": survey, "categories": categories}
        if form.is_valid():
            return self.treat_valid_form(form, kwargs, request, survey)
        return self.handle_invalid_form(context, form, request, survey)

    @staticmethod
    def handle_invalid_form(context, form, request, survey):
        LOGGER.info("Non valid form: <%s>", form)
        if survey.template is not None and len(survey.template) > 4:
            template_name = survey.template
        else:
            if survey.is_all_in_one_page():
                template_name = "okr/one_page_survey.html"
            else:
                template_name = "okr/survey.html"
        return render(request, template_name, context)

    def treat_valid_form(self, form, kwargs, request, survey):
        session_key = "survey_%s" % (kwargs["id"],)
        if session_key not in request.session:
            request.session[session_key] = {}
        for key, value in list(form.cleaned_data.items()):
            request.session[session_key][key] = value
            request.session.modified = True
        next_url = form.next_step_url()
        response = None
        if survey.is_all_in_one_page():
            response = form.save()
        else:
            # when it's the last step
            if not form.has_next_step():
                save_form = ResponseForm(request.session[session_key], survey=survey, user=request.user)
                if save_form.is_valid():
                    response = save_form.save()
                else:
                    LOGGER.warning("A step of the multipage form failed but should have been discovered before.")
        # if there is a next step
        if next_url is not None:
            return redirect(next_url)
        del request.session[session_key]
        if response is None:
            return redirect(reverse("okr:survey-list"))
        next_ = request.session.get("next", None)
        if next_ is not None:
            if "next" in request.session:
                del request.session["next"]
            return redirect(next_)
        return redirect("okr:survey-confirmation", uuid=response.interview_uuid)


def serve_unprotected_result_csv(survey):
    """ Return the csv corresponding to a survey. """
    survey_to_csv = Survey2Csv(survey)
    if survey_to_csv.need_update():
        survey_to_csv.generate_file()
    with open(survey_to_csv.filename, "r") as csv_file:
        response = HttpResponse(csv_file.read(), content_type="text/csv")
    content_disposition = 'attachment; filename="{}.csv"'.format(survey.name)
    response["Content-Disposition"] = content_disposition
    return response


@login_required
def serve_protected_result(request, survey):
    """ Return the csv only if the user is logged. """
    return serve_unprotected_result_csv(survey)


def serve_result_csv(request, primary_key):
    """ ... only if the survey does not require login or the user is logged.

    :param int primary_key: The primary key of the survey. """
    survey = get_object_or_404(Survey, pk=primary_key)
    if not survey.is_published:
        messages.error(request, "This survey has not been published")
        return redirect("%s?next=%s" % (settings.LOGIN_URL, request.path))
    if survey.need_logged_user:
        return serve_protected_result(request, survey)
    return serve_unprotected_result_csv(survey)

zerone_inc/users/api/views.py
from django.contrib.auth import get_user_model
from rest_framework import status
from rest_framework.decorators import action
from rest_framework.mixins import ListModelMixin, RetrieveModelMixin, UpdateModelMixin
from rest_framework.response import Response
from rest_framework.viewsets import GenericViewSet

from .serializers import UserSerializer

User = get_user_model()


class UserViewSet(RetrieveModelMixin, ListModelMixin, UpdateModelMixin, GenericViewSet):
    serializer_class = UserSerializer
    queryset = User.objects.all()
    lookup_field = "username"

    def get_queryset(self, *args, **kwargs):
        return self.queryset.filter(id=self.request.user.id)

    @action(detail=False, methods=["GET"])
    def me(self, request):
        serializer = UserSerializer(request.user, context={"request": request})
        return Response(status=status.HTTP_200_OK, data=serializer.data)

zerone_inc/users/views.py
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView
import jdatetime
User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    slug_field = "username"
    slug_url_kwarg = "username"

    def get_context_data(self, **kwargs):
        context = super(UserDetailView, self).get_context_data(**kwargs)
        context['current_year'] = jdatetime.date.today().year
        context['current_month'] = jdatetime.date.today().month

        return context


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, UpdateView):
    model = User
    fields = ["first_name",
              "last_name",
              "title"]

    def get_success_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})

    def get_object(self):
        return User.objects.get(username=self.request.user.username)

    def form_valid(self, form):
        messages.add_message(
            self.request, messages.INFO, _("Infos successfully updated")
        )
        return super().form_valid(form)


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

zerone_inc/templates/zeroslack/base.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
  {{ block.super }}
  {% block extracss %}

  {% endblock %}
{% endblock %}
{% block content %}
  <section class="team-grid" id="team">
  <div class="container" id="wrap">
    {% block wrapper %}{% endblock %}

      {% block body %}

      {% endblock %}

  </div>
  </section>
{% endblock content %}


{% block javascript %}
  {{ block.super }}
  {% block extrajs %}

  {% endblock %}
{% endblock %}

zerone_inc/templates/zeroslack/graph.html
{% extends 'zeroslack/base.html' %}

{% block extracss %}
  <link href="https://fonts.googleapis.com/css?family=Raleway:400,300,600,800,900" rel="stylesheet" type="text/css">
  <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.21/css/jquery.dataTables.css">

{% endblock %}

{% block body %}
  <div class="well row" id="container-main">
    <div class="col-md-4 btn-cont d-flex justify-content-center align-content-center">
      <a class="btn-slice" href="{% url 'zeroslack:dashboard' prev_year prev_month %}">
        <div class="top"><span>{{ prev_month_label }}</span></div>
        <div class="bottom"><span>{{ prev_month_label }}</span></div>
      </a>

    </div>
    <div id="intro" class="col-md-4 justify-content-center align-items-center">
      <h3 class="text-uppercase text-center text-secondary">Your Attendance</h3>
      <hr class="star-dark mb-5">
      {% if attendance_overall %}
        <div class="attendance-progress"></div>
      {% else %}
        <div class="well row" id="container-main">
          <div class="col-md-12">
            <h1 class="h1"> There is nothing here... </h1>
          </div>
        </div>
      {% endif %}
    </div>
    <div class="col-md-4 btn-cont d-flex justify-content-center align-content-center">
      <a class="btn-slice" href="{% url 'zeroslack:dashboard' next_year next_month %}">
        <div class="top"><span>{{ next_month_label }}</span></div>
        <div class="bottom"><span>{{ next_month_label }}</span></div>
      </a>
    </div>
  </div>
  <hr class="star-dark mb-5">
  {% if attendance_overall %}
  <div class="well row" id="container-main">
    <div class="col-md-12">
      <table id="example" class="table table-striped table-bordered" style="width:100%">
        <thead>
        <tr>
          <th>ID</th>
          <th>Username</th>
          <th>Sign In Date</th>
          <th>Sign Out Date</th>
          <th>Sign In Persian</th>
          <th>Sign Out Persian</th>
        </tr>
        </thead>
        <tfoot>
        <tr>
          <th>ID</th>
          <th>Username</th>
          <th>Sign In Date</th>
          <th>Sign Out Date</th>
          <th>Sign In Persian</th>
          <th>Sign Out Persian</th>
        </tr>
        </tfoot>
      </table>
    </div>
  </div>
  {% endif %}
{% endblock %}
{% block extrajs %}
  <script src="https://rawgit.com/kimmobrunfeldt/progressbar.js/1.0.0/dist/progressbar.js"></script>
  <script type="text/javascript" charset="utf8"
          src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.js"></script>
  <script type="application/javascript">
    $(document).ready(function () {
      // progressbar.js@1.0.0 version is used
// Docs: http://progressbarjs.readthedocs.org/en/1.0.0/
      function secondsToHms(d) {
        d = Number(d);
        let h = Math.floor(d / 3600);
        let m = Math.floor(d % 3600 / 60);
        let hDisplay = h > 0 ? h + " h," : "";
        let mDisplay = m > 0 ? m + " m" : "";
        return hDisplay + mDisplay;
      }


      let bar = new ProgressBar.SemiCircle(".attendance-progress", {
        strokeWidth: 6,
        color: '#FFEA82',
        trailColor: '#eee',
        trailWidth: 1,
        easing: 'easeInOut',
        duration: 1400,
        svgStyle: null,
        text: {
          value: '',
          alignToBottom: false
        },
        from: {color: '#ED6A5A'},
        to: {color: '#4ADBC8'},
//  from: { color: '#B1C1C0', width: 1 },
//  to: { color: '#CBD081', width: 5 },
        // Set default step function for all animate calls
        step: (state, bar) => {
          bar.path.setAttribute('stroke', state.color);
          var value = (bar.value() * 691200);
          bar.setText(secondsToHms(value));
          bar.text.style.color = state.color;
        }
      });

      bar.text.style.fontFamily = '"Raleway", Helvetica, sans-serif';
      bar.text.style.fontSize = '1.5rem';

      bar.animate({{ attendance_overall }});  // Number from 0.0 to 1.0

      $('#example').DataTable({
        "ajax": {
          url: "{% url 'zeroslack:dashboard-table' year month %}",
          dataSrc: 'data'
        },
        "processing": true,
        "columns": [
          {"data": "id"},
          {"data": "user"},
          {"data": "sign_in"},
          {"data": "sign_out"},
          {"data": "sign_in_persian"},
          {"data": "sign_out_persian"}
        ]
      });
    });
  </script>
{% endblock %}